print("Hello")
Print("Learing Git& GitHub")
#learing Git- Git status
________________________________________________________________________

"""
git add. Usage: git add [file] ...
git commit. Usage: git commit -m “[ Type in the commit message]” ...
git diff. Usage: git diff. ...
git reset. Usage: git reset [file] ...
git log. Usage: git log. ...
git branch. Usage: git branch. ...
git checkout. Usage: git checkout [branch name] ...
git push. Usage: git push [variable name] master

"""
